name: smart_home_app
description: Advanced Smart Home Control Application with Voice, Security, and Energy Management

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Network & API
  http: ^1.1.0
  dio: ^5.3.2
  web_socket_channel: ^2.4.0
  mqtt_client: ^10.0.0

  # UI Components
  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.5.0
  flutter_animate: ^4.2.0
  lottie: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_card_swiper: ^6.0.0

  # Audio & Voice
  speech_to_text: ^6.3.0
  flutter_tts: ^3.8.5
  audio_waveforms: ^1.0.5

  # Camera & Media
  camera: ^0.10.5
  image_picker: ^1.0.4
  video_player: ^2.7.2

  # Biometric & Security
  local_auth: ^2.1.6
  crypto: ^3.0.3
  encrypt: ^5.0.1

  # Sensors & Hardware
  sensors_plus: ^4.0.2
  battery_plus: ^5.0.1
  device_info_plus: ^9.1.0
  permission_handler: ^11.0.1

  # Storage & Database
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Location & Maps
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0

  # Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0

  # Charts & Analytics
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.2.7

  # Utils
  intl: ^0.18.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700